version: "3"

services:
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.18
    volumes:
      - ${MQTT_CFG_PATH}:/mosquitto/config/mosquitto.conf
      - ${MQTT_DATA_PATH}:/mosquitto/data
      - ${MQTT_LOG_PATH}:/mosquitto/log
      - ${MQTT_PASSWD_FILE}:/mosquitto/passwd_file  
    env_file:
      - .env
    restart: always
    ports:
      - ${DOCKER_MQTT_BROKER_INIT_PORT}:1883
      - ${DOCKER_MQTT_WEB_INIT_PORT}:9001

  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - mqtt
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  grafana-storage:
  influxdb-storage:
  config:
  data:
  log:
